"""add cost_per_distance and total_cost cols to trips table

Revision ID: 219524615b11
Revises: 34e258a9a977
Create Date: 2025-10-26 12:11:12.233480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '219524615b11'
down_revision = '34e258a9a977'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('cost_per_distance', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('trips', sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'total_cost')
    op.drop_column('trips', 'cost_per_distance')
    # ### end Alembic commands ###