"""drop distance_unit columns

Revision ID: 34e258a9a977
Revises: e595bb84b4a9
Create Date: 2025-10-25 23:45:55.860891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34e258a9a977'
down_revision = 'e595bb84b4a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'distance_unit')
    op.drop_column('trips', 'distance_unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('distance_unit', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    op.add_column('groups', sa.Column('distance_unit', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
    # ### end Alembic commands ###