"""change cost per distance to 2 decimal places

Revision ID: 7cb095a1f5fb
Revises: af3778090226
Create Date: 2025-10-08 23:32:44.749992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cb095a1f5fb'
down_revision = 'af3778090226'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'cost_per_distance',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('groups', 'cost_per_distance',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=10, scale=4),
               existing_nullable=False)
    # ### end Alembic commands ###