"""change created_by col to user_id in trips table

Revision ID: bf1af7c4c038
Revises: de2f7f500cfa
Create Date: 2025-10-26 13:12:47.669502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf1af7c4c038'
down_revision = 'de2f7f500cfa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('trips_created_by_fkey', 'trips', type_='foreignkey')
    op.create_foreign_key(None, 'trips', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('trips', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'trips', type_='foreignkey')
    op.create_foreign_key('trips_created_by_fkey', 'trips', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_column('trips', 'user_id')
    # ### end Alembic commands ###