"""create trips table

Revision ID: e595bb84b4a9
Revises: 48a6755fb36e
Create Date: 2025-10-20 23:28:32.485929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e595bb84b4a9'
down_revision = '48a6755fb36e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('stops', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_distance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('distance_unit', sa.String(length=2), nullable=False),
    sa.CheckConstraint("distance_unit IN ('km', 'mi')", name='check_distance_unit_valid'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips')
    # ### end Alembic commands ###