"""create new settled_at col for trips table

Revision ID: f1cc1910dfea
Revises: bf1af7c4c038
Create Date: 2025-10-26 14:11:29.826364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1cc1910dfea'
down_revision = 'bf1af7c4c038'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'settled_at')
    # ### end Alembic commands ###